Repository NLGS2907/Hackers-Panas-TP2, pull requests merged in 2021-07, with the labels that each got.

#11 Actualizar TDAs (IMPORTANTE)
  .gitignore
  CONTRIBUTING.md
  EasyBMP.cpp
  EasyBMP.h
  EasyBMP_BMP.h
  EasyBMP_DataStructures.h
  EasyBMP_Geometry.cpp
  EasyBMP_Geometry.h
  EasyBMP_VariousBMPutilities.h
  README.md
  casillero.h
  constantes.h
  docs/DocumentacionEasyBMP/EasyBMP_UserManual.pdf
  docs/imgInforme/Cubo.png
  docs/imgInforme/Cubo_Coordenadas.png
  docs/imgInforme/Cubo_Limpio.png
  exportador.cpp
  exportador.h
  exportadorTDA.h
  listaLigada.h
  nodo.h
  principal.cpp
  tablero.h
Labels: Interfaz, TDAs, documentación, mejora

#12 TDA Lista re-hecho por completo
  README.md
  casillero.h
  cubo.cpp
  cubo.h
  exportador.cpp
  listaLigada.h
  nodo.h
  tablero.h
Labels: TDAs

#13 Agregado método ganoAlguien()
  casillero.h
  constantes.h
  exportador.cpp
  exportadorTDA.h
  tablero.h
Labels: TDAs, gameplay, mejora

#6 Agrego TDA Mazo y TDA Carta. Usan nodo.h
  carta.cpp
  carta.h
  cola.h
  mazo.cpp
  mazo.h
Labels: TDAs, gameplay, mejora

#10 TDA Juego y TDA Jugador
  Juego.cpp
  Juego.h
  Jugador.cpp
  Jugador.h
Labels: TDAs, gameplay, mejora

#14 Versión Casi Final del TP
  Juego.cpp
  Juego.h
  Jugador.cpp
  Jugador.h
  carta.cpp
  carta.h
  casillero.h
  cola.h
  constantes.h
  exportadorTDA.h
  mazo.cpp
  mazo.h
  menu.cpp
  menu.h
  principal.cpp
  tablero.h
Labels: Interfaz, documentación, gameplay
